"""
Explore the project's data dictionary (docs/data_dictionary/*.csv) from
Python - what tables exist, and what every field in a table means,
how it's derived, and whether it's safe to use as a same-game
predictor. Reads the dictionary CSVs generated by
scripts/build_data_dictionary.R - not the actual parquet data itself
(see load_data.py for that).
"""
from pathlib import Path
from typing import Optional

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DICTIONARY_DIR = PROJECT_ROOT / "docs" / "data_dictionary"


def _dictionary_files():
    if not DICTIONARY_DIR.exists():
        raise FileNotFoundError(
            f"{DICTIONARY_DIR} not found - run `Rscript scripts/build_data_dictionary.R` "
            f"from the project root first."
        )
    return sorted(DICTIONARY_DIR.glob("*.csv"))


def _load_table_dictionary(table_name: str) -> pd.DataFrame:
    path = DICTIONARY_DIR / f"{table_name}.csv"
    if not path.exists():
        available = ", ".join(f.stem for f in _dictionary_files())
        raise FileNotFoundError(f"No dictionary for '{table_name}'. Available tables: {available}")
    return pd.read_csv(path)


def list_tables(print_output: bool = True) -> pd.DataFrame:
    """Every table the pipeline documents: name, description, column
    count, and core source tables. Returns a DataFrame either way;
    prints a readable summary unless print_output=False."""
    rows = []
    for f in _dictionary_files():
        df = _load_table_dictionary(f.stem)
        table_row = df.loc[df["row_num"] == 1].iloc[0]
        rows.append({
            "table": table_row["name"],
            "description": table_row["description"],
            "n_columns": len(df) - 1,
            "sources": table_row["sources"],
        })
    result = pd.DataFrame(rows)

    if print_output:
        print(f"{len(result)} tables in {DICTIONARY_DIR.relative_to(PROJECT_ROOT)}\n")
        for _, r in result.iterrows():
            print(f"{r['table']}  ({r['n_columns']} columns)")
            print(f"    {r['description']}")
            print(f"    sources: {r['sources']}\n")

    return result


def list_fields(
    table_name: str,
    feature_family: Optional[str] = None,
    leakage_risk: Optional[str] = None,
    print_output: bool = True,
) -> pd.DataFrame:
    """Every field in `table_name`: description, derivation logic,
    source column(s), dtype, feature_family, and leakage_risk.

    Optionally narrow it down:
      feature_family - exact match, e.g. "own_rolling", "matchup",
                        "identifier" (see docs/data_dictionary/README.md
                        for the full list of tags)
      leakage_risk    - substring match (case-insensitive), e.g.
                        "UNSAFE" to find same-game actuals to avoid as
                        predictors, or "safe" for everything usable
                        pre-game

    Returns a DataFrame either way; prints a readable summary unless
    print_output=False.
    """
    df = _load_table_dictionary(table_name)
    fields = df.loc[df["row_num"] > 1].drop(columns="row_num").reset_index(drop=True)

    if feature_family is not None:
        fields = fields.loc[fields["feature_family"] == feature_family]
    if leakage_risk is not None:
        fields = fields.loc[
            fields["leakage_risk"].astype(str).str.contains(leakage_risk, case=False, na=False)
        ]

    if print_output:
        header = f"{table_name}: {len(fields)} field(s)"
        if feature_family is not None:
            header += f"  [feature_family = '{feature_family}']"
        if leakage_risk is not None:
            header += f"  [leakage_risk contains '{leakage_risk}']"
        print(header + "\n")

        for _, r in fields.iterrows():
            print(f"{r['name']}  ({r['dtype']}, {r['feature_family']})")
            print(f"    {r['description']}")
            if pd.notna(r["logic"]):
                print(f"    logic:   {r['logic']}")
            if pd.notna(r["sources"]):
                print(f"    sources: {r['sources']}")
            if pd.notna(r["leakage_risk"]):
                print(f"    leakage: {r['leakage_risk']}")
            print()

    return fields


if __name__ == "__main__":
    list_tables()
    print("-" * 70)
    list_fields("team_rebounding_features")
